

* Once you update your repository, copy all the contents of the fullstack-course4/assignments/assignment5/assignment5-solution-starter folder into your newly created solutions container folder for this assignment, e.g., module5-solution.

*** Once that's done, you are ready to start coding the solution.

*** NOTE: the provided code will not run. It is up to you to follow the instructions to get it to run.

*** You are NOT allowed to change the home-snippet.html file. Any adjustments to the value of randomCategoryShortName property needs to be done in Javascript code.

* There are 4-5 fairly simple steps to implement the required functionality.

*** Open up js/script.js file.
*** Find TODO: STEP 0, and follow the instructions until you are done with TODO: STEP 4.
    If you've watched the lectures, the code should be very familiar to you.

* Once you are done, verify that the desired functionality is working correctly.
  Use Browser Sync or deploy your solution to GitHub pages.
*** TODO Load the home page in the browser.
*** TODO Click on the Specials tile. 
    A single page category with a list of menu items for some category should appear.
*** TODO Click on the restaurant logo to go back to the home page.
*** TODO Click on the Specials tile again.
    Most likely, a different single page category page will be shown.
*** TODO Repeat this several times 
    to make sure that most of the time you see a different single category page.
